# Generated by Django 5.2.6 on 2026-08-31 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expected_census', models.IntegerField(default=15)),
                ('required_staff', models.IntegerField(default=4)),
                ('available_staff', models.IntegerField(default=3)),
                ('shortage', models.IntegerField(default=1)),
                ('surplus', models.IntegerField(default=0)),
                ('forecast_accuracy', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='facilities.facility')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.ward')),
            ],
        ),
    ]
