# Generated by Django 5.2.6 on 2026-08-31 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('professionals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('required_workers', models.IntegerField(default=1)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('incentive', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('break_duration', models.IntegerField(default=30, help_text='Break duration in minutes')),
                ('recurrence', models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='NONE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FILLED', 'Filled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], default='DRAFT', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='facilities.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='facilities.facility')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.healthcarerole')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.specialty')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='facilities.ward')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='CONFIRMED', max_length=30)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('compliance_checked_at', models.DateTimeField(blank=True, null=True)),
                ('compliance_override_reason', models.TextField(blank=True, null=True)),
                ('compliance_overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_overrides', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='professionals.professionalprofile')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='shifts.shift')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=30)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='professionals.professionalprofile')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='shifts.shift')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('EXPIRED', 'Expired')], default='APPLIED', max_length=30)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='professionals.professionalprofile')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='shifts.shift')),
            ],
            options={
                'unique_together': {('shift', 'professional')},
            },
        ),
    ]
