# Generated by Django 5.2.6 on 2026-08-31 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_by_default', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='professionals/')),
                ('professional_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('years_experience', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(default='English', max_length=200)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('ON_LEAVE', 'On Leave'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=30)),
                ('preferred_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('minimum_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('preferred_commute_distance', models.IntegerField(default=50, help_text='in km')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('reliability_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('performance_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_facilities', models.ManyToManyField(blank=True, related_name='preferred_by_professionals', to='facilities.facility')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.healthcarerole')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_shift_types', models.CharField(default='DAY,NIGHT,EVENING', max_length=200)),
                ('preferred_days', models.CharField(default='0,1,2,3,4,5,6', max_length=200)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='professionals.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=200)),
                ('policy_number', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('document', models.FileField(blank=True, null=True, upload_to='insurance/')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='professionals.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='professionals.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_number', models.CharField(max_length=100)),
                ('issuing_authority', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('document', models.FileField(upload_to='credentials/')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('RESTRICTED', 'Restricted')], default='PENDING', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_credentials', to=settings.AUTH_USER_MODEL)),
                ('credential_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.credentialtype')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='professionals.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_body', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='qualifications/')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='professionals.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_histories', to='professionals.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('shift_type', models.CharField(choices=[('DAY', 'Day'), ('NIGHT', 'Night'), ('EVENING', 'Evening')], max_length=20)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='professionals.professionalprofile')),
            ],
            options={
                'unique_together': {('professional', 'day_of_week', 'shift_type')},
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='professionals.professionalprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.skill')),
            ],
            options={
                'unique_together': {('professional', 'skill')},
            },
        ),
    ]
